config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :delivery_partners
  devise_for :customers

  resources :shipments, only: [:index, :new, :create] do
    put 'update_status', on: :member
  end

  put 'delivery_partner/update_availability', to: 'delivery_partner#update_avilability'

  # Defines the root path route ("/")
  root "shipments#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipments
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email"]
  end
end

app/models/delivery_partner.rb
class DeliveryPartner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :shipments
  validates :name, presence: true

  scope :available, -> { 
    where(active_for_delivery: true)
  }

  def self.least_shipments_with_pending_or_shipped
    available.min_by do |partner|
      partner.shipments.where(status: ["pending", "shipped"]).count
    end
  end


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email"]
  end

end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :customer
  belongs_to :delivery_partner, optional: true

  validates :source, :target, :item, presence: true

  validates :status, presence: true, on: :update

  enum status: [:pending, :shipped, :delivered, :cancelled]

  before_create :set_default_status_and_partner

  def set_default_status_and_partner
    self.status = :pending
    self.delivery_partner = DeliveryPartner.least_shipments_with_pending_or_shipped
  end

  validate :not_cancelled_after_shipped_or_delivered, if: :status_changed?

  private

  def not_cancelled_after_shipped_or_delivered
    if ((status == "cancelled") || (status == "pending")) && (status_was == 'shipped' || status_was == 'delivered')
      errors.add(:status, "can't be cancelled after shipment is shipped or delivered")
    elsif (status == "shipped") && (status_was == 'delivered')
      errors.add(:status, "can't be shipped after shipment is delivered")
    elsif status_was == 'cancelled' && (status == 'shipped' || status == 'delivered')
      errors.add(:status, "can't be shipped after shipment is cancelled")
    end
  end


  def self.ransackable_associations(auth_object = nil)
    ["customer", "delivery_partner"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["customer_id", "delivery_partner_id", "item", "source", "status", "target"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/delivery_partner_controller.rb
class DeliveryPartnerController < ApplicationController
  before_action :authenticate_delivery_partner!

  def update_avilability
    @delivery_partner = current_delivery_partner
    @delivery_partner.update(active_for_delivery: params[:available])
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace('delivery_partner_status', partial: "shared/delivery_partners/status_button")
      }
    end
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :authenticate_user, only: [:index, :update_status]
  before_action :authenticate_customer!, only: [:new, :create]

  def index
    if current_customer
      @non_deliver_shipments = current_customer.shipments.includes(:delivery_partner).not_delivered
      @deliver_shipments = current_customer.shipments.includes(:delivery_partner).delivered
      render 'shared/customers/shipment_index'
    elsif current_delivery_partner
      @delivery_partner = current_delivery_partner
      @non_deliver_shipments = current_delivery_partner.shipments.includes(:customer).not_delivered.not_cancelled
      @deliver_shipments = current_delivery_partner.shipments.includes(:customer).delivered.not_cancelled
      render 'shared/delivery_partners/shipment_index'
    end
  end

  def new
    @shipment = Shipment.new
  end

  def create
    @shipment = current_customer.shipments.build(shipment_params)
    if @shipment.save
      redirect_to shipments_path, notice: "Shipment created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update_status
    @shipment = Shipment.find(params[:id])
    template = current_customer ? 'shared/customers/status_form' : 'shared/delivery_partners/status_form'
    respond_to do |format|
      if @shipment.update(status: params[:status])
        format.turbo_stream { render turbo_stream: turbo_stream.replace("status_form_#{@shipment.id}", partial: template, locals: { shipment: @shipment }) }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("status_form_#{@shipment.id}", partial: template, locals: { shipment: @shipment.reload }) }
      end
    end
  end

  private

  def shipment_params
    params.require(:shipment).permit(:source, :target, :item)
  end

  def authenticate_user
    unless (customer_signed_in? || delivery_partner_signed_in?)
      redirect_to new_customer_session_path
    end
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delivery_partner_helper.rb
module DeliveryPartnerHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasShipmentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "SaaS Shipment App", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "My Shipments", shipments_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create Shipment", new_shipment_path, class: "nav-link" %>
          </li>
        <% elsif delivery_partner_signed_in? %>
          <li class="nav-item">
            <%= link_to "Assigned Shipments", shipments_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if customer_signed_in?%>
          <li class="nav-item">
            <%= link_to "Logout", destroy_customer_session_path, class: "nav-link", data: {turbo_method: :delete} %>
          </li>
        <% elsif delivery_partner_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_delivery_partner_session_path, class: "nav-link", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <% unless exclude.any?(:customer) %>
            <li class="nav-item">
                <%= link_to "Customer Login", new_customer_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Customer Signup", new_customer_registration_path, class: "nav-link" %>
            </li>
          <% end %>
          <% unless exclude.any?(:delivery_partner) %>
            <li class="nav-item">
                <%= link_to "Delivery Partner Login", new_delivery_partner_session_path, class: "nav-link" %>
            </li>
            
            <li class="nav-item">
                <%= link_to "Delivery Partner Signup", new_delivery_partner_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/customers/_shipment.html.erb
<tr>
  <td><%= shipment.source %></td>
  <td><%= shipment.target %></td>
  <td><%= shipment.item %></td>
  <td><%= render "shared/customers/status_form", shipment: shipment %></td>
  <td><%= shipment.delivery_partner&.name %></td>
</tr>

app/views/shared/customers/_status_form.html.erb
<% if ['pending', 'cancelled'].any?(shipment.status) %>
  <%= turbo_frame_tag "status_form_#{shipment.id}" do %>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= shipment.status %>
      </button>
      <ul class="dropdown-menu">
        <%= form_with(url: update_status_shipment_path(shipment), method: :put, class: "dropdown-form") do |form| %>
          <%= form.hidden_field :status, value: "pending" %>
          <%= form.submit "Pending", class: "dropdown-item", data: { turbo_frame: "status_form_#{shipment.id}" } %>
        <% end %>

        <%= form_with(url: update_status_shipment_path(shipment), method: :put, class: "dropdown-form") do |form| %>
          <%= form.hidden_field :status, value: "cancelled" %>
          <%= form.submit "Cancelled", class: "dropdown-item", data: { turbo_frame: "status_form_#{shipment.id}" } %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% else %>
  <button class="btn btn-secondary" type="button" aria-expanded="false">
    <%= shipment.status %>
  </button>
<% end %>  

app/views/shared/customers/shipment_index.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">
  <% if @non_deliver_shipments.present? %>
    <h1 class="mb-4">Your Shipments</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Source</th>
          <th>Target</th>
          <th>Item</th>
          <th>Status</th>
          <th>Delivered By</th>
        </tr>
      </thead>
      <tbody>
        <% @non_deliver_shipments.each do |shipment| %>
          <%= render partial: 'shared/customers/shipment', locals: {shipment: shipment} %>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <% if @deliver_shipments.present? %>
    <h1 class="mb-4">Deliverd Shipments</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Source</th>
          <th>Target</th>
          <th>Item</th>
          <th>Status</th>
          <th>Delivered By</th>
        </tr>
      </thead>
      <tbody>
        <% @deliver_shipments.each do |shipment| %>
        <tr>
          <td><%= shipment.source %></td>
          <td><%= shipment.target %></td>
          <td><%= shipment.item %></td>
          <td>
            <button class="btn btn-secondary" type="button" aria-expanded="false">
              <%= shipment.status %>
            </button>
          </td>
          <td><%= shipment.delivery_partner&.name %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @non_deliver_shipments.empty? && @deliver_shipments.empty? %>
    <p>No shipments found.</p>
  <% end %>
</div>

app/views/shared/delivery_partners/_shipment.html.erb
 <tr>
  <td><%= shipment.source %></td>
  <td><%= shipment.target %></td>
  <td><%= shipment.item %></td>
  <td><%= render "shared/delivery_partners/status_form", shipment: shipment %></td>
  <td><%= shipment.customer.name %></td>
</tr>

app/views/shared/delivery_partners/_status_button.html.erb
<%= turbo_frame_tag "delivery_partner_status" do %>
  <% if @delivery_partner.active_for_delivery %>
    <%= button_to "Inactive", delivery_partner_update_availability_path, method: :put, params: { available: false }, class: "btn btn-primary mb-3" %>
  <% else %>
    <%= button_to "Active", delivery_partner_update_availability_path, method: :put, params: { available: true }, class: "btn btn-primary mb-3" %>
  <% end %>
<% end %>

app/views/shared/delivery_partners/_status_form.html.erb
<% if ['pending', 'shipped'].any?(shipment.status) %>
  <%= turbo_frame_tag "status_form_#{shipment.id}" do %>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= shipment.status %>
      </button>
      <ul class="dropdown-menu">
        <% if shipment.pending? %>
          <%= form_with(url: update_status_shipment_path(shipment), method: :put, class: "dropdown-form") do |form| %>
          <%= form.hidden_field :status, value: "shipped" %>
          <%= form.submit "Shipped", class: "dropdown-item", data: { turbo_frame: "status_form_#{shipment.id}" } %>
          <% end %>
        <% end %>

        <% if shipment.shipped? %>
          <%= form_with(url: update_status_shipment_path(shipment), method: :put, class: "dropdown-form") do |form| %>
          <%= form.hidden_field :status, value: "delivered" %>
          <%= form.submit "Delivered", class: "dropdown-item", data: { turbo_frame: "status_form_#{shipment.id}" } %>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
<% else %>
  <button class="btn btn-secondary" type="button" aria-expanded="false">
    <%= shipment.status %>
  </button>
<% end %>  

app/views/shared/delivery_partners/shipment_index.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">

  <%= render partial: 'shared/delivery_partners/status_button' %>

  <br/>

  <% if @non_deliver_shipments.present? %>
    <h1 class="mb-4">Assigned Shipments</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Source</th>
          <th>Target</th>
          <th>Item</th>
          <th>Status</th>
          <th>Order By</th>
        </tr>
      </thead>
      <tbody>
        <% @non_deliver_shipments.each do |shipment| %>
          <%= render partial: 'shared/delivery_partners/shipment', locals: {shipment: shipment} %>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <% if @deliver_shipments.present? %>
    <h1 class="mb-4">Deliverd Shipments</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Source</th>
          <th>Target</th>
          <th>Item</th>
          <th>Status</th>
          <th>Order By</th>
        </tr>
      </thead>
      <tbody>
        <% @deliver_shipments.each do |shipment| %>
           <tr>
            <td><%= shipment.source %></td>
            <td><%= shipment.target %></td>
            <td><%= shipment.item %></td>
            <td>
              <button class="btn btn-secondary" type="button" aria-expanded="false">
                <%= shipment.status %>
              </button>
            </td>
            <td><%= shipment.customer.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
  <% if @non_deliver_shipments.empty? && @deliver_shipments.empty? %>
    <p>No assigned shipments found.</p>
  <% end %>
</div>

app/views/shipments/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">
  
  <h1 class="mb-4">Create Shipment</h1>
  <% if @shipment.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" data-turbo-cache="false">
        <h2>
        <%= I18n.t("errors.messages.not_saved",
                    count: @shipment.errors.count,
                    resource: 'shipment')
        %>
        </h2>
        <ul>
        <% @shipment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
  <% end %>

  <%= form_with model: @shipment, url: shipments_path, method: :post do |f| %>
    <div class="mb-3">
      <%= f.label :source, class: "form-label" %>
      <%= f.text_field :source, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :target, class: "form-label" %>
      <%= f.text_field :target, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :item, class: "form-label" %>
      <%= f.text_field :item, class: "form-control" %>
    </div>
  <%= f.submit "Create Shipment", class: "btn btn-primary" %>
  <% end %>
</div>